# Generated by Django 3.0.2 on 2020-01-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_name',
            field=models.CharField(max_length=100, verbose_name='username'),
        ),
    ]
